version: '2'

services:
  db:
    image: mysql:latest
    env_file: .env
  pma:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - "1987:80"
    links:
      - db:database
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
        - ./docker/vhost.conf:/etc/apache2/sites-enabled/mapicoin.conf
        - .:/var/www/html
