version: '2'

services:
  db:
    image: mysql:latest
    env_file: .env
  pma:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - "1987:80"
    links:
      - db
  web:
    image: php:7-apache
    links:
      - db
    ports:
      - "8080:80"
    volumes:
        - .:/var/www/html
